spring:
    kafka:
        bootstrap-servers: 127.0.0.1:19092,127.0.0.1:29092,127.0.0.1:39092
        consumer:
            auto-offset-reset: earliest
            group-id: codelearn-group

---
app:
    kafka:
        topic1: generic-topic
        topic2: person-topic
        topic3: customer-topic
