spring:
    kafka:
        bootstrap-servers: 127.0.0.1:19092,127.0.0.1:29092,127.0.0.1:39092
        producer:
            client-id: local-producer-1
            retries: 3
            properties:
                spring.json.type.mapping: customer:gr.codelearn.spring.kafka.domain.Customer,person:gr.codelearn.spring.kafka.domain.Person
    task:
        execution:
            pool:
                core-size: 2
            thread-name-prefix: scheduler-

---
app:
    kafka:
        topic1: generic-topic
        topic2: person-topic
        topic3: customer-topic
